name = "Tango"
license = "MIT"
licenselink = "https://lab.wtfteam.pro/fat0troll/hugo-tango-theme/blob/master/LICENSE"
description = "Hugo Theme inspired by linux.org.ru default theme"
homepage = "https://lab.wtfteam.pro/fat0troll/hugo-tango-theme"
tags = ["blog","minimal","responsive","dark"]
features = ["blog","font-awesome"]
min_version = "0.33"

[author]
  name = "Vladimir Hodakov"
  homepage = "https://blog.hodakov.me/"
